### ISSUE TITLE
Only show in tab the first time install devtron

### ISSUE THREAD

**Issue by jwu** [electron/devtron#59]
The DevTron tab only show up on the first time `require('devtron').install()`. When you close the devtools, and open it again, you'll find the tab gone, and even if you recall the `install()` it will not appear.

**Comment by kevinsawicki** [comment]
Thanks for reporting this, it looks like this might be an Electron bug https://github.com/electron/electron/pull/5490

**Comment by kevinsawicki** [comment]
Electron 1.0.1 is out which should have this issue address, thanks again 👍
