### ISSUE TITLE
Does not run when devtools are undocked

### ISSUE THREAD

**Issue by smwhit** [electron/devtron#60]
Hi
We've updated our electron app to 1.0.1, and npm installed devtron.

However the tab does not appear when running require('devtron').install() in the console.

Any ideas what we can check?

Thanks

Simon

**Comment by kevinsawicki** [comment]
Do any errors appear?

**Comment by smwhit** [comment]
Nope:

require('devtron').install()
undefined

**Comment by kevinsawicki** [comment]
So no tab appears to the right of the Audits tab?

Sometimes new tabs offscreen by default if the dev tools window isn't wide enough to show them all and instead it puts them in the `>>` menu at the right.

**Comment by smwhit** [comment]
I already checked that it wasn't offscreen!

I'm showing the debug tools via:
`require('electron-debug')({ enabled: true, showDevTools: true })`

This brings up the dev tools for the rendered process. Is this the correct place to run the devtron command?

**Comment by kevinsawicki** [comment]
>  Is this the correct place to run the devtron command?

Yup, that should be the place, not sure what is going on, is your app public by any chance?

**Comment by smwhit** [comment]
Unfortunately it's not.

**Comment by kevinsawicki** [comment]
@smwhit I added a bit more logging in #61 

Can you try `devtron@1.0.1` and see what it prints when you run it with that version? Try running `require('devtron').uninstall()` before reinstalling as well.

**Comment by smwhit** [comment]
Ok, I get:

require('devtron').install()
2016-05-11 16:14:34.000 D:\project_path\node_modules\devtron\api.js:4 Installing Devtron from D:\project_path\node_modules\devtron
"devtron"

**Comment by kevinsawicki** [comment]
> Ok, I get:

That all looks good, hmm.

Does your app show the dev tools for a `<webview>` tag by any chance instead of for the main window?

**Comment by smwhit** [comment]
We don't use webview in our app...

**Comment by kevinsawicki** [comment]
If you look at the standard out from your app, do you see any errors logged there when you run `require('devtron')install()`?

Might looking something like:

> [24473:0511/172342:ERROR:CONSOLE(7)] "Uncaught Error: chrome is not defined", source: chrome-extension://extension-1/static/devtron.html (7)

**Comment by kevinsawicki** [comment]
Also, what platform are you on and do you have the dev tools docked or in a floating window?

**Comment by smwhit** [comment]
It's windows 7 64bit, and dev tools are floating.

**Comment by kevinsawicki** [comment]
> It's windows 7 64bit, and dev tools are floating.

Okay, good to know. Sorry that devtron isn't working for you. I'll take a look on Windows and post back here once I know more.

**Comment by kevinsawicki** [comment]
> dev tools are floating.

Can you try docking them, then closing and reopening and seeing if the tab appears?

**Comment by smwhit** [comment]
Ok
Running install, then docking, makes it appear. Undocking shows two "Devtron" tabs
I do need to do this each time I launch the app, but it's working

Thanks for producing this tool. I could have done with it last week when I had issues "webpack"ing our app and had require issues when packaging.

**Comment by kevinsawicki** [comment]
Looks related to https://github.com/electron/electron/issues/4958

**Comment by kevinsawicki** [comment]
I believe this has been fixed in Electron 1.1.0 so I'm going to close this out here since this should no longer be an issue on the latest devtron/electron versions. Thanks again for reporting.
