### ISSUE TITLE
"Listen for crash events" warning showing, not correct?

### ISSUE THREAD

**Issue by bengotow** [electron/devtron#67]
Hey! Devtron is awesome, but it's giving this warning in the Lint panel:

![image](https://cloud.githubusercontent.com/assets/1037212/15230051/b7f04128-1848-11e6-858f-7219531a56bf.png)

However, we do have a listener attached https://github.com/nylas/N1/blob/master/src/browser/nylas-window.coffee#L198, and I can verify that it's working properly by force-emitting a crashed event from the dev tools console within the window:

`remote.getCurrentWebContents().emit('crashed')`

Maybe it's not picking it up because the listener is in the main process and not within the renderer process?

**Comment by kevinsawicki** [comment]
This should now be fixed in `1.1.1` via #68, thanks @princejwesley
