### ISSUE TITLE
Event Listeners and IPC no outputs

### ISSUE THREAD

**Issue by nvcwk** [electron/devtron#83]
New to programming electron and devtron

# Environment
* Operating system: Linux Mint 17.1
* Node: v4.4.7
* Electron: v1.1.3 
* Devtron: v1.2.1

# Issue
Tried Devtron with electron v1.1.3, there are no outputs for Event Listeners and IPC. Oddly, tried with electron v1.2.7 and v1.0.1, there are outputs for the Event Listeners but IPC still remains empty. Below are the outputs of Require Graph, Event listeners and IPC for the three electron versions.

**Electron v1.1.3 Outputs**

- Main process => 1-line output 
- Render Process => Output is normal
- Event Listeners => Zero output
- IPC => Zero output

**Electron v1.0.1 Outputs**

- Main process => 1-line output 
- Render Process => Output is normal
- Event Listeners => Output is normal
- IPC => Zero output

**Electron v1.2.7 Outputs**

- Main process => 1-line output 
- Render Process => Output is normal
- Event Listeners => Output is normal
- IPC => Zero output

**Would greatly appreciate if someone could point the steps in resolving this issue. Thanks!** 

# Main.js
This is how devtron is installed and uninstalled via the Main.js:

```
const app = require('electron').app;
const BrowserWindow = require('electron').BrowserWindow;
const cwd = require('electron').app.getAppPath();

var mainWindow = null;

app.on('ready', function() {
  require('devtron').install();

  mainWindow = new BrowserWindow({width: 1400, height: 800});
  mainWindow.loadURL('file://' + cwd + '/Index.html');
  mainWindow.webContents.openDevTools();
  
  mainWindow.on('closed', function () {
    mainWindow = null;
  });
});

app.on('window-all-closed', function () {
  require('devtron').uninstall();

  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', function () {
  if (mainWindow === null) {
    app.createWindow();
  }
});
```

**Comment by kevinsawicki** [comment]
> but IPC still remains empty. 

Just want to confirm that you have clicked the record button on the toolbar.

> Main process => 1-line output

Can you include a screenshot of this line?
