### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by shrynx** [electron/devtron#92]
I am unable to use devtron, only a blank page appears. and in the Terminal it shows 
[15462:1022/132742:ERROR:CONSOLE(206)] "Uncaught SyntaxError: Unexpected token {", source: chrome-extension://extension-1/out/index.js (206)

**Comment by kevinsawicki** [comment]
What version of Electron are you using and what version of devtron are you using?

**Comment by shrynx** [comment]
Ahhh, sorry. It was a legacy project using an old electron. I updated it and it is working now.
Thanks for the tool btw, is it possible to provide stats over which electron helper process is consuming how much memory and why ?

**Comment by shrynx** [comment]
@kevinsawicki closing this issue, but i would love to have the above mentioned feature. Should i open a new thread ?
